server:
  shutdown: graceful
  servlet:
    session:
      timeout: 10800
      cookie:
        name: SESSION
        http-only: true
        path: /
        max-age: 10800
        secure: ${COOKIE_SECURE:false}
        same-site: ${COOKIE_SAME_SITE:lax}
logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: account_email
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: kakao_account
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
  web:
    resources:
      add-mappings: false
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket-name: ${AWS_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      sns:
        region: ${AWS_SNS_REGION}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  http:
    converters:
      preferred-json-mapper: jackson
auth:
  allowed-origins:
      - '*'
schedule:
  oneseoSubmissionStart: ${ONESEO_SUBMISSION_START}
  oneseoSubmissionEnd: ${ONESEO_SUBMISSION_END}
  firstResultsAnnouncement: ${FIRST_RESULTS_ANNOUNCEMENT}
  competencyEvaluation: ${COMPETENCY_EVALUATION}
  interview: ${INTERVIEW}
  finalResultsAnnouncement: ${FINAL_RESULTS_ANNOUNCEMENT}

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: ${ACTUATOR_BASE_PATH}
  endpoint:
    prometheus:
      access: read_only
discord-alarm:
  url: ${DISCORD_RELAY_SERVER_URL}
  api-key: ${DISCORD_RELAY_SERVER_API_KEY}
disender:
  webhook-url: ${DISENDER_WEBHOOK_URL}
lambda-score-calculator:
  url: ${SCORE_CALCULATOR_SERVICE_URL}
  api-key: ${SCORE_CALCULATOR_API_KEY}

sdk:
  logging:
    enabled: true
    not-logging-urls:
      - "/api-docs/**"
      - "/swagger-ui/**"
      - "/hello-management/prometheus/**"

  response:
    enabled: true
    not-wrapping-urls:
      - "/api-docs/**"
      - "/hello-management/prometheus/**"

  exception:
    enabled: false


  swagger:
    enabled: false
